import { useState } from "react"

// Sample doctor data with departments
const doctors = [
  { id: 1, name: "Dr. Sarah Johnson", department: "Cardiology" },
  { id: 2, name: "Dr. Michael Smith", department: "Pediatrics" },
  { id: 3, name: "Dr. Emily Davis", department: "Orthopedics" }
]

export default function VisitDetails() {
  const [selectedDoctor, setSelectedDoctor] = useState("")
  const [department, setDepartment] = useState("")

  const handleDoctorChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const doctorName = e.target.value
    setSelectedDoctor(doctorName)
    
    // Find the selected doctor and set the department
    const doctor = doctors.find(doc => doc.name === doctorName)
    if (doctor) {
      setDepartment(doctor.department)
    } else {
      setDepartment("")
    }
  }
  return (
    <div className="bg-white rounded-b-lg shadow-sm p-6">
      <h2 className="text-xl font-semibold text-gray-900 mb-2">Visit Details</h2>
      <hr className="mb-6"/>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Visit ID</label>
          <input
            type="text"
            placeholder="VST-DDYYYYXXXX"
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Date of Examination</label>
          <input
            type="date"
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Time of Examination</label>
          <input
            type="time"
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Doctor</label>
          <select 
            value={selectedDoctor}
            onChange={handleDoctorChange}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option value="">Select a Doctor</option>
            {doctors.map((doctor) => (
              <option key={doctor.id} value={doctor.name}>
                {doctor.name}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Department</label>
          <input
            type="text"
            value={department}
            readOnly
            placeholder="Department will be auto-filled"
            className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">Generated by</label>
          <input
            type="text"
            placeholder="EMP ID of User"
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
      </div>

      <div className="mt-6">
         <button className="bg-blue-500 hover:bg-blue-700 text-white px-6 py-2 rounded-md text-sm font-medium">
          Send for Vitals
        </button>
      </div>
    </div>
  )
}
